services:
  app:
    image: node:lts-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run test:jest"
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://user:password@db:5432/testdb
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb